import { LibraryTrait } from '../traitLibrary';

export const MAGITECH_TRAITS: LibraryTrait[] = [
    // --- BACKGROUNDS (20) ---
    { name: "Elite Soldier", category: 'background', requiredConfig: 'Magitech', description: "Trained in a secret program, your body has been enhanced with infused mako-like energy.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Athletics' }, { type: 'save', bonus: 1, abilityName: 'strength' }], tags: ['background', 'elite'] },
    { name: "Aether-Tech Engineer", category: 'background', requiredConfig: 'Magitech', description: "You maintain the massive crystal reactors that power the high-cities.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Artifice' }, { type: 'skill', bonus: 1, skillName: 'Technology' }], tags: ['background', 'technical'] },
    { name: "Sky-Pirate", category: 'background', requiredConfig: 'Magitech', description: "The clouds are your home, and laws are just suggestions for ground-dwellers.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Operate Vehicle' }, { type: 'skill', bonus: 1, skillName: 'Deception' }], tags: ['background', 'renegade'] },
    { name: "Materia Scholar", category: 'background', requiredConfig: 'Magitech', description: "Spent years researching how to condense raw mana into usable orbs of power.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Arcana' }, { type: 'skill', bonus: 1, skillName: 'Science' }], tags: ['background', 'academic'] },
    { name: "Sector Scavenger", category: 'background', requiredConfig: 'Magitech', description: "Grew up in the lower plates, picking through the scraps of the wealthy above.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Thievery' }, { type: 'skill', bonus: 1, skillName: 'Stealth' }], tags: ['background', 'survival'] },
    { name: "High-City Envoy", category: 'background', requiredConfig: 'Magitech', description: "You are accustomed to the crystalline towers and corporate etiquette of the capital.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Civics' }, { type: 'skill', bonus: 1, skillName: 'Persuasion' }], tags: ['background', 'social'] },
    { name: "Ancient Bloodline", category: 'background', requiredConfig: 'Magitech', description: "Your ancestors spoke to the planet itself; you hear echoes of their power.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Aether Sense' }, { type: 'skill', bonus: 1, skillName: 'History' }], tags: ['background', 'mythic'] },
    { name: "Beast Arena Tamer", category: 'background', requiredConfig: 'Magitech', description: "You earned your keep managing the bio-engineered creatures of the coliseum.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Athletics' }, { type: 'skill', bonus: 1, skillName: 'Medicine' }], tags: ['background', 'martial'] },
    { name: "Resistance Operative", category: 'background', requiredConfig: 'Magitech', description: "Working from the shadows to dismantle the corporate aether-monopoly.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Stealth' }, { type: 'skill', bonus: 1, skillName: 'Investigation' }], tags: ['background', 'rebel'] },
    { name: "Mana-Cell Courier", category: 'background', requiredConfig: 'Magitech', description: "Dangerous high-speed delivery of unstable crystalline energy.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Acrobatics' }, { type: 'skill', bonus: 1, skillName: 'Operate Vehicle' }], tags: ['background', 'hustle'] },
    { name: "Corporate Assassin", category: 'background', requiredConfig: 'Magitech', description: "A professional cleaner for the board of directors.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Deception' }, { type: 'skill', bonus: 1, skillName: 'Stealth' }], tags: ['background', 'lethal'] },
    { name: "Guardian of the Fane", category: 'background', requiredConfig: 'Magitech', description: "Protector of the natural crystal springs that pre-date modern technology.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Aether Sense' }, { type: 'skill', bonus: 1, skillName: 'Survival' }], tags: ['background', 'divine'] },
    { name: "Ex-Experimental Subject", category: 'background', requiredConfig: 'Magitech', description: "You escaped a lab that attempted to graft aether-conduits into your nervous system.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Insight' }, { type: 'save', bonus: 1, abilityName: 'constitution' }], tags: ['background', 'hardened'] },
    { name: "Public Servant", category: 'background', requiredConfig: 'Magitech', description: "Managing the complex bureaucracy of a magitech metropolis.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Civics' }, { type: 'skill', bonus: 1, skillName: 'Investigation' }], tags: ['background', 'corporate'] },
    { name: "Urban Explorer", category: 'background', requiredConfig: 'Magitech', description: "You know every duct and secret passage of the megastructure.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Acrobatics' }, { type: 'skill', bonus: 1, skillName: 'Perception' }], tags: ['background', 'exploration'] },
    { name: "Magitek Pilot", category: 'background', requiredConfig: 'Magitech', description: "You were trained to operate the heavy bio-mechanical combat suits.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Operate Vehicle' }, { type: 'skill', bonus: 1, skillName: 'Technology' }], tags: ['background', 'military'] },
    { name: "Aether-Wave DJ", category: 'background', requiredConfig: 'Magitech', description: "Manipulating the frequency of mana to entertain the masses.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Performance' }, { type: 'skill', bonus: 1, skillName: 'Technology' }], tags: ['background', 'social'] },
    { name: "Crystalline Jeweler", category: 'background', requiredConfig: 'Magitech', description: "Cutting and polishing mana-conduits for high-end gear.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Artifice' }, { type: 'skill', bonus: 1, skillName: 'Insight' }], tags: ['background', 'craft'] },
    { name: "Void-Runner", category: 'background', requiredConfig: 'Magitech', description: "Illegal racing through aetheric slipstreams in the upper atmosphere.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'Operate Vehicle' }, { type: 'skill', bonus: 1, skillName: 'Athletics' }], tags: ['background', 'hustle'] },
    { name: "Relic Hunter", category: 'background', requiredConfig: 'Magitech', description: "Seeking out pre-calamity tech from the ruins of the Old World.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 1, skillName: 'History' }, { type: 'skill', bonus: 1, skillName: 'Investigation' }], tags: ['background', 'exploration'] },

    // --- VESSEL HULLS (10) ---
    { name: "Aether-Shielded Hull", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "Sleek, white-alloy plating infused with glowing mana-barriers.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'ac', bonus: 2 }], tags: ['ship', 'defense'] },
    { name: "Gravity-Lift Stabilizers", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "Floating geometric nodes that ignore the weight of the vessel.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'save', bonus: 2, abilityName: 'dexterity' }], tags: ['ship', 'speed'] },
    { name: "Bio-Organic Core", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "A semi-living power source that self-heals structural integrity.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'ability', bonus: 2, abilityName: 'constitution' }], tags: ['ship', 'vitality'] },
    { name: "Crystalline Keel", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "A focused mana-channeling spine providing surgical handling.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'ability', bonus: 2, abilityName: 'dexterity' }], tags: ['ship', 'speed'] },
    { name: "Magitek Piston Prow", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "High-output kinetic hammers in the prow for ramming maneuvers.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'ability', bonus: 2, abilityName: 'strength' }], tags: ['ship', 'force'] },
    { name: "Prismatic Plating", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "Reflective scales that dissipate elemental and arcane energy.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'resistance', bonus: 0, damageType: 'Radiant' }], tags: ['ship', 'defense'] },
    { name: "Officer's Sky-Lounge", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "Grand panoramic command deck that inspires crew confidence.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'save', bonus: 2, abilityName: 'charisma' }], tags: ['ship', 'social'] },
    { name: "Tactical Data-Nexus", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "A mainframe that processes thousands of battlefield simulations per second.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'save', bonus: 2, abilityName: 'intelligence' }], tags: ['ship', 'knowledge'] },
    { name: "Aether-Resonance Grid", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "Sensors that feel the 'rhythm' of incoming threats before they occur.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'save', bonus: 2, abilityName: 'wisdom' }], tags: ['ship', 'utility'] },
    { name: "Heavy Displacement Plating", category: 'ship_hull', isShipOnly: true, requiredConfig: 'Magitech', description: "Massive slabs of magically-hardened alloy to anchor the vessel.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'save', bonus: 2, abilityName: 'strength' }], tags: ['ship', 'defense'] },

    // --- VESSEL MODULES (10) ---
    { name: "Mana-Scan Lenses", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "Crystalline eyes that see magical heat and hidden signatures.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 2, skillName: 'Perception' }], tags: ['ship', 'utility'] },
    { name: "Diagnostic Scrying-Pool", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "An aetheric liquid pool that visualizes structural weaknesses and clues.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 2, skillName: 'Investigation' }], tags: ['ship', 'utility'] },
    { name: "Slipstream Sails", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "Glowing energy sails that catch the 'currents' of high-altitude mana.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 2, skillName: 'Operate Vehicle' }], tags: ['ship', 'utility'] },
    { name: "Void-Shimmer Stealth", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "Partially phases the vessel into the rift to hide from sight.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 2, skillName: 'Stealth' }], tags: ['ship', 'utility'] },
    { name: "Amplified Rune-Voice", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "Magical amplifiers for grand announcements and diplomatic parley.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 2, skillName: 'Persuasion' }], tags: ['ship', 'utility'] },
    { name: "Artificer's Workshop", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "A well-equipped bay for the crafting and repair of magical devices.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 2, skillName: 'Artifice' }], tags: ['ship', 'utility'] },
    { name: "Homing Mana-Batteries", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "Automated turrets that lock onto aetheric signatures with precision.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'attack', bonus: 2 }], tags: ['ship', 'offensive'] },
    { name: "Photon Thrusters", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "Direct-light propulsion providing superior physical speed and force.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'skill', bonus: 2, skillName: 'Athletics' }], tags: ['ship', 'speed'] },
    { name: "Voltage Dampeners", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "Insulated grounding points to absorb voltaic mana surges.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'resistance', bonus: 0, damageType: 'Electric' }], tags: ['ship', 'defense'] },
    { name: "Refractive Hull Coating", category: 'ship_module', isShipOnly: true, requiredConfig: 'Magitech', description: "A shifting crystal layer that bends light and fire away from the hull.", usage: { type: 'passive', maxUses: 0, currentUses: 0 }, buffs: [{ type: 'resistance', bonus: 0, damageType: 'Fire' }], tags: ['ship', 'defense'] }
];
